import { Workout } from "./types";

// Used only if the live API fails to respond, so the site never breaks.
export const FALLBACK_WORKOUTS: Workout[] = [
  {
    id: "1",
    name: "BARBELL BENCH PRESS",
    category: ["CHEST", "ARMS"],
    equipment: "Barbell, Bench",
    image: "/banner.png",
    duration: 25,
    calories: 180,
    rating: 4.8,
    difficulty: "Intermediate",
    sets: 4,
    reps: "6-8",
    description:
      "A compound press that builds chest thickness, triceps, and pressing power from a stable bench.",
    instructions: [
      "Lie flat on the bench with feet planted firmly on the floor.",
      "Grip the bar slightly wider than shoulder-width and unrack it.",
      "Lower the bar under control until it lightly touches your chest.",
      "Press the bar back up to full lockout without bouncing.",
    ],
  },
  {
    id: "2",
    name: "RUSSIAN TWIST",
    category: ["CORE"],
    equipment: "Medicine Ball",
    image: "/banner.png",
    duration: 12,
    calories: 90,
    rating: 4.5,
    difficulty: "Beginner",
    sets: 3,
    reps: "20",
    description:
      "A rotational core movement that builds obliques and trains anti-rotation control.",
    instructions: [
      "Sit on the floor with knees bent and lean back slightly.",
      "Hold the medicine ball with both hands in front of your chest.",
      "Rotate your torso to tap the ball on the floor beside your hip.",
      "Rotate to the other side and repeat for the set.",
    ],
  },
  {
    id: "3",
    name: "BACK SQUAT",
    category: ["LEGS"],
    equipment: "Barbell, Rack",
    image: "/banner.png",
    duration: 30,
    calories: 260,
    rating: 4.9,
    difficulty: "Intermediate",
    sets: 4,
    reps: "5",
    description:
      "The king of leg exercises, building total-body strength through the quads, glutes, and core.",
    instructions: [
      "Set the bar on your upper back and unrack it with a tight core.",
      "Step back and set your feet shoulder-width apart.",
      "Bend your knees and hips to sit down until thighs are parallel to the floor.",
      "Drive through your heels to stand back up to full lockout.",
    ],
  },
  {
    id: "4",
    name: "PULL-UP",
    category: ["BACK", "ARMS"],
    equipment: "Pull-up Bar",
    image: "/banner.png",
    duration: 15,
    calories: 140,
    rating: 4.7,
    difficulty: "Advanced",
    sets: 4,
    reps: "8-10",
    description:
      "A bodyweight pulling move that builds a wider back and stronger grip.",
    instructions: [
      "Hang from the bar with an overhand grip, hands wider than shoulders.",
      "Pull your chest up toward the bar by driving your elbows down.",
      "Pause briefly at the top with your chin over the bar.",
      "Lower back down under control to a full hang.",
    ],
  },
  {
    id: "5",
    name: "DUMBBELL SHOULDER PRESS",
    category: ["SHOULDERS", "ARMS"],
    equipment: "Dumbbells, Bench",
    image: "/banner.png",
    duration: 20,
    calories: 150,
    rating: 4.6,
    difficulty: "Beginner",
    sets: 3,
    reps: "10",
    description:
      "Builds round, strong shoulders and improves overhead pressing stability.",
    instructions: [
      "Sit upright on a bench holding a dumbbell in each hand at shoulder height.",
      "Brace your core and press both dumbbells straight overhead.",
      "Pause briefly at the top without locking out hard.",
      "Lower back down slowly to shoulder height and repeat.",
    ],
  },
  {
    id: "6",
    name: "ROMANIAN DEADLIFT",
    category: ["LEGS", "BACK"],
    equipment: "Barbell",
    image: "/banner.png",
    duration: 22,
    calories: 200,
    rating: 4.7,
    difficulty: "Intermediate",
    sets: 4,
    reps: "8",
    description:
      "A hip-hinge movement that targets the hamstrings and glutes while sparing the lower back.",
    instructions: [
      "Hold the bar with a shoulder-width grip, standing tall.",
      "Push your hips back while keeping the bar close to your legs.",
      "Lower until you feel a deep hamstring stretch, keeping your back flat.",
      "Drive your hips forward to return to standing.",
    ],
  },
  {
    id: "7",
    name: "PLANK",
    category: ["CORE"],
    equipment: "Bodyweight",
    image: "/banner.png",
    duration: 8,
    calories: 45,
    rating: 4.3,
    difficulty: "Beginner",
    sets: 3,
    reps: "45 sec",
    description:
      "An isometric core hold that builds total-body stability and a stronger midsection.",
    instructions: [
      "Get into a forearm plank with elbows under your shoulders.",
      "Keep your body in a straight line from head to heels.",
      "Brace your core and squeeze your glutes to avoid sagging.",
      "Hold for the full duration while breathing steadily.",
    ],
  },
  {
    id: "8",
    name: "BARBELL BICEP CURL",
    category: ["ARMS"],
    equipment: "Barbell",
    image: "/banner.png",
    duration: 14,
    calories: 95,
    rating: 4.4,
    difficulty: "Beginner",
    sets: 3,
    reps: "10-12",
    description:
      "A classic isolation move that builds thicker, stronger biceps.",
    instructions: [
      "Stand tall holding the bar with an underhand, shoulder-width grip.",
      "Keep your elbows pinned to your sides throughout the movement.",
      "Curl the bar up toward your chest, squeezing your biceps.",
      "Lower the bar back down under control to full extension.",
    ],
  },
  {
    id: "9",
    name: "LEG PRESS",
    category: ["LEGS"],
    equipment: "Leg Press Machine",
    image: "/banner.png",
    duration: 18,
    calories: 170,
    rating: 4.5,
    difficulty: "Beginner",
    sets: 4,
    reps: "10",
    description:
      "A machine-based leg movement that safely overloads the quads and glutes.",
    instructions: [
      "Sit in the machine with feet shoulder-width apart on the platform.",
      "Release the safety and lower the platform until knees reach about 90 degrees.",
      "Press through your heels to extend your legs without locking your knees.",
      "Control the platform back down and repeat.",
    ],
  },
  {
    id: "10",
    name: "LAT PULLDOWN",
    category: ["BACK"],
    equipment: "Cable Machine",
    image: "/banner.png",
    duration: 16,
    calories: 120,
    rating: 4.5,
    difficulty: "Beginner",
    sets: 3,
    reps: "10-12",
    description:
      "A back-width builder that's a great pull-up alternative for beginners.",
    instructions: [
      "Sit at the machine and grip the bar wider than shoulder-width.",
      "Lean back slightly and pull the bar down to your upper chest.",
      "Squeeze your shoulder blades together at the bottom of the movement.",
      "Let the bar rise back up under control to full extension.",
    ],
  },
  {
    id: "11",
    name: "TRICEP DIP",
    category: ["ARMS", "CHEST"],
    equipment: "Dip Bars",
    image: "/banner.png",
    duration: 12,
    calories: 100,
    rating: 4.4,
    difficulty: "Intermediate",
    sets: 3,
    reps: "10",
    description:
      "A bodyweight push movement that hammers the triceps and lower chest.",
    instructions: [
      "Grip the dip bars and support your body with arms extended.",
      "Lower your body by bending your elbows, keeping them close.",
      "Descend until your shoulders are just below your elbows.",
      "Press back up to full lockout without flaring your elbows.",
    ],
  },
  {
    id: "12",
    name: "KETTLEBELL SWING",
    category: ["LEGS", "CORE"],
    equipment: "Kettlebell",
    image: "/banner.png",
    duration: 15,
    calories: 210,
    rating: 4.6,
    difficulty: "Intermediate",
    sets: 4,
    reps: "15",
    description:
      "An explosive hip-hinge movement that builds power and conditioning at once.",
    instructions: [
      "Stand with feet shoulder-width apart, kettlebell on the floor in front of you.",
      "Hinge at the hips and swing the kettlebell back between your legs.",
      "Drive your hips forward explosively to swing the bell to chest height.",
      "Let it swing back down and repeat for the set.",
    ],
  },
];